package net.geoprism.account;

@com.runwaysdk.business.ClassSignature(hash = 1417163902)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to OauthServer.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class OauthServerQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = 1417163902;

  protected OauthServerQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.account.OauthServerDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.account.OauthServerDTO>)super.getResultSet();
}
}
