package net.geoprism.data.etl;

@com.runwaysdk.business.ClassSignature(hash = 1150673790)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to UnknownClassifierException.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class UnknownClassifierExceptionBase extends com.runwaysdk.business.SmartException implements com.runwaysdk.generation.loader.Reloadable
{
  public final static String CLASS = "net.geoprism.data.etl.UnknownClassifierException";
  public static java.lang.String CLASSIFIERLABEL = "classifierLabel";
  public static java.lang.String ID = "id";
  private static final long serialVersionUID = 1150673790;
  
  public UnknownClassifierExceptionBase()
  {
    super();
  }
  
  public UnknownClassifierExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public UnknownClassifierExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public UnknownClassifierExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public String getClassifierLabel()
  {
    return getValue(CLASSIFIERLABEL);
  }
  
  public void validateClassifierLabel()
  {
    this.validateAttribute(CLASSIFIERLABEL);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF getClassifierLabelMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.data.etl.UnknownClassifierException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF)mdClassIF.definesAttribute(CLASSIFIERLABEL);
  }
  
  public void setClassifierLabel(String value)
  {
    if(value == null)
    {
      setValue(CLASSIFIERLABEL, "");
    }
    else
    {
      setValue(CLASSIFIERLABEL, value);
    }
  }
  
  public String getId()
  {
    return getValue(ID);
  }
  
  public void validateId()
  {
    this.validateAttribute(ID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF getIdMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.data.etl.UnknownClassifierException.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF)mdClassIF.definesAttribute(ID);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    java.lang.String message = super.localize(locale);
    message = replace(message, "{classifierLabel}", this.getClassifierLabel());
    message = replace(message, "{id}", this.getId());
    return message;
  }
  
}
