package com.runwaysdk.geodashboard.gis.persist;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 *
 * @author Autogenerated by RunwaySDK
 */
@com.runwaysdk.business.ClassSignature(hash = 511454561)
public enum AllAggregationType implements com.runwaysdk.business.BusinessEnumeration, com.runwaysdk.generation.loader.Reloadable
{
  AVG(),
  
  DISTRIBUTION(),
  
  MAJORITY(),
  
  MAX(),
  
  MIN(),
  
  MINORITY(),
  
  SUM();
  
  public static final java.lang.String CLASS = "com.runwaysdk.geodashboard.gis.persist.AllAggregationType";
  private com.runwaysdk.geodashboard.gis.persist.AggregationType enumeration;
  
  private synchronized void loadEnumeration()
  {
    com.runwaysdk.geodashboard.gis.persist.AggregationType enu = com.runwaysdk.geodashboard.gis.persist.AggregationType.getEnumeration(this.name());
    setEnumeration(enu);
  }
  
  private synchronized void setEnumeration(com.runwaysdk.geodashboard.gis.persist.AggregationType enumeration)
  {
    this.enumeration = enumeration;
  }
  
  public java.lang.String getId()
  {
    loadEnumeration();
    return enumeration.getId();
  }
  
  public java.lang.String getEnumName()
  {
    loadEnumeration();
    return enumeration.getEnumName();
  }
  
  public java.lang.String getDisplayLabel()
  {
    loadEnumeration();
    return enumeration.getDisplayLabel().getValue(com.runwaysdk.session.Session.getCurrentLocale());
  }
  
  public static AllAggregationType get(String id)
  {
    for (AllAggregationType e : AllAggregationType.values())
    {
      if (e.getId().equals(id))
      {
        return e;
      }
    }
    return null;
  }
  
}
