/**
 * Copyright (c) 2015 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Runway SDK(tm).
 *
 * Runway SDK(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Runway SDK(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package net.geoprism.data.browser;

@com.runwaysdk.business.ClassSignature(hash = 369166289)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MetadataType.java
 *
 * @author Autogenerated by RunwaySDK
 */
public  abstract  class MetadataTypeQueryBase extends com.runwaysdk.query.GeneratedViewQuery
 implements com.runwaysdk.generation.loader.Reloadable
{

  public MetadataTypeQueryBase(com.runwaysdk.query.QueryFactory componentQueryFactory)
  {
    super(componentQueryFactory);
  }

  public MetadataTypeQueryBase(com.runwaysdk.query.QueryFactory componentQueryFactory, com.runwaysdk.query.ViewQueryBuilder viewQueryBuilder)
  {
    super(componentQueryFactory, viewQueryBuilder);
  }
  public String getClassType()
  {
    return net.geoprism.data.browser.MetadataType.CLASS;
  }
  public com.runwaysdk.query.SelectableChar getDisplayLabel()
  {
    return getDisplayLabel(null);

  }
 
  public com.runwaysdk.query.SelectableChar getDisplayLabel(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.DISPLAYLABEL, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getDisplayLabel(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.DISPLAYLABEL, alias, displayLabel);

  }
 
  public com.runwaysdk.query.SelectableChar getId()
  {
    return getId(null);

  }
 
  public com.runwaysdk.query.SelectableChar getId(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.ID, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getId(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.ID, alias, displayLabel);

  }
 
  public com.runwaysdk.query.SelectableChar getParentTypeId()
  {
    return getParentTypeId(null);

  }
 
  public com.runwaysdk.query.SelectableChar getParentTypeId(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.PARENTTYPEID, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getParentTypeId(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.PARENTTYPEID, alias, displayLabel);

  }
 
  public com.runwaysdk.query.SelectableChar getTypeId()
  {
    return getTypeId(null);

  }
 
  public com.runwaysdk.query.SelectableChar getTypeId(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.TYPEID, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getTypeId(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.TYPEID, alias, displayLabel);

  }
 
  public com.runwaysdk.query.SelectableChar getTypeName()
  {
    return getTypeName(null);

  }
 
  public com.runwaysdk.query.SelectableChar getTypeName(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.TYPENAME, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getTypeName(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.TYPENAME, alias, displayLabel);

  }
 
  public com.runwaysdk.query.SelectableChar getTypePackage()
  {
    return getTypePackage(null);

  }
 
  public com.runwaysdk.query.SelectableChar getTypePackage(String alias)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.TYPEPACKAGE, alias, null);

  }
 
  public com.runwaysdk.query.SelectableChar getTypePackage(String alias, String displayLabel)
  {
    return (com.runwaysdk.query.SelectableChar)this.getSelectable(net.geoprism.data.browser.MetadataType.TYPEPACKAGE, alias, displayLabel);

  }
 
  /**  
   * Returns an iterator of Business objects that match the query criteria specified
   * on this query object. 
   * @return iterator of Business objects that match the query criteria specified
   * on this query object.
   */
  @java.lang.SuppressWarnings("unchecked")
  public com.runwaysdk.query.OIterator<? extends MetadataType> getIterator()
  {
    com.runwaysdk.query.ValueIterator valueIterator;
    if (_pageSize != null && _pageNumber != null)
    {
      valueIterator = (com.runwaysdk.query.ValueIterator<com.runwaysdk.dataaccess.ValueObject>)this.getComponentQuery().getIterator(_pageSize, _pageNumber);
    }
    else
    {
      valueIterator = (com.runwaysdk.query.ValueIterator<com.runwaysdk.dataaccess.ValueObject>)this.getComponentQuery().getIterator();
    }
    return new com.runwaysdk.query.ViewIterator<MetadataType>(this.getMdClassIF(), valueIterator);
  }

}
