package net.geoprism.data.etl.excel;

@com.runwaysdk.business.ClassSignature(hash = 2125888676)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DataUploaderImportJob.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class DataUploaderImportJobQueryDTO extends com.runwaysdk.system.scheduler.ExecutableJobQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = 2125888676;

  protected DataUploaderImportJobQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.data.etl.excel.DataUploaderImportJobDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.data.etl.excel.DataUploaderImportJobDTO>)super.getResultSet();
}
}
