package com.runwaysdk.geodashboard.gis.persist;

/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 *
 * @author Autogenerated by RunwaySDK
 */
@com.runwaysdk.business.ClassSignature(hash = -1562886687)
public enum AllAggregationTypeDTO implements com.runwaysdk.business.EnumerationDTOIF, com.runwaysdk.generation.loader.Reloadable
{
  AVG(),
  
  DISTRIBUTION(),
  
  MAJORITY(),
  
  MAX(),
  
  MIN(),
  
  MINORITY(),
  
  SUM();
  
  public final static String CLASS = "com.runwaysdk.geodashboard.gis.persist.AllAggregationType";
  
  
  public com.runwaysdk.geodashboard.gis.persist.AggregationTypeDTO item(com.runwaysdk.constants.ClientRequestIF clientRequest)
  {
    return (com.runwaysdk.geodashboard.gis.persist.AggregationTypeDTO) clientRequest.getEnumeration(com.runwaysdk.geodashboard.gis.persist.AllAggregationTypeDTO.CLASS, this.name());
  }
  
  @java.lang.SuppressWarnings("unchecked")
  public static java.util.List<com.runwaysdk.geodashboard.gis.persist.AggregationTypeDTO> items(com.runwaysdk.constants.ClientRequestIF clientRequest, AllAggregationTypeDTO ... items)
  {
    java.lang.String[] itemNames = new java.lang.String[items.length];
    for(int i=0; i<items.length; i++)
    {
      itemNames[i] = items[i].name();
    }
    return (java.util.List<com.runwaysdk.geodashboard.gis.persist.AggregationTypeDTO>) clientRequest.getEnumerations(com.runwaysdk.geodashboard.gis.persist.AllAggregationTypeDTO.CLASS, itemNames);
  }
  
  @java.lang.SuppressWarnings("unchecked")
  public static java.util.List<com.runwaysdk.geodashboard.gis.persist.AggregationTypeDTO> allItems(com.runwaysdk.constants.ClientRequestIF clientRequest)
  {
    return (java.util.List<com.runwaysdk.geodashboard.gis.persist.AggregationTypeDTO>) clientRequest.getAllEnumerations(com.runwaysdk.geodashboard.gis.persist.AllAggregationTypeDTO.CLASS);
  }
  
  public java.lang.String getName()
  {
    return this.name();
  }
}
