package com.runwaysdk.geodashboard.gis.persist;

@com.runwaysdk.business.ClassSignature(hash = -908640407)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AggregationStrategyView.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class AggregationStrategyViewQueryDTO extends com.runwaysdk.business.ViewQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = -908640407;

  protected AggregationStrategyViewQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.geodashboard.gis.persist.AggregationStrategyViewDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.geodashboard.gis.persist.AggregationStrategyViewDTO>)super.getResultSet();
}
}
