package com.runwaysdk.geodashboard.gis.persist.condition;

@com.runwaysdk.business.ClassSignature(hash = -1130194194)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DashboardOr.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class DashboardOrQueryDTO extends com.runwaysdk.geodashboard.gis.persist.condition.DashboardCompositeQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = -1130194194;

  protected DashboardOrQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.geodashboard.gis.persist.condition.DashboardOrDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.geodashboard.gis.persist.condition.DashboardOrDTO>)super.getResultSet();
}
}
