package com.runwaysdk.geodashboard.gis.persist.condition;

@com.runwaysdk.business.ClassSignature(hash = 502137486)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DashboardGreaterThan.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class DashboardGreaterThanQueryDTO extends com.runwaysdk.geodashboard.gis.persist.condition.DashboardPrimitiveQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = 502137486;

  protected DashboardGreaterThanQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.geodashboard.gis.persist.condition.DashboardGreaterThanDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.geodashboard.gis.persist.condition.DashboardGreaterThanDTO>)super.getResultSet();
}
}
