package com.runwaysdk.geodashboard;

/**
 *
 * @author Autogenerated by RunwaySDK
 */
public class MdAttributeViewQuery extends com.runwaysdk.geodashboard.MdAttributeViewQueryBase  implements com.runwaysdk.generation.loader.Reloadable
{

  public MdAttributeViewQuery(com.runwaysdk.query.QueryFactory queryFactory)
  {
    super(queryFactory);
    this.buildQuery(new DefaultMdAttributeViewBuilder(queryFactory));
  }

  public MdAttributeViewQuery(com.runwaysdk.query.QueryFactory queryFactory, com.runwaysdk.query.ViewQueryBuilder viewQueryBuilder)
  {
    super(queryFactory, viewQueryBuilder);
  }

  class DefaultMdAttributeViewBuilder extends com.runwaysdk.query.ViewQueryBuilder implements com.runwaysdk.generation.loader.Reloadable
  {
    public DefaultMdAttributeViewBuilder(com.runwaysdk.query.QueryFactory queryFactory)
    {
      super(queryFactory);
    }

    protected MdAttributeViewQuery getViewQuery()
    {
      return (MdAttributeViewQuery)super.getViewQuery();
    }

    /**
     * build the select clause
     */
    protected void buildSelectClause()
    {
      String errMsg = "buildSelectClause() method in class DefaultMdAttributeViewBuilder needs to be overwritten.";
      throw new com.runwaysdk.query.QueryException(errMsg);
    }

    /**
     * Implement only if additional join criteria is required.
     */
    protected void buildWhereClause()
    {

    }

  }
}
