package com.runwaysdk.geodashboard;

@com.runwaysdk.business.ClassSignature(hash = -1580001584)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DashboardMetadata.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class DashboardMetadataQueryDTO extends com.runwaysdk.business.RelationshipQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = -1580001584;

  protected DashboardMetadataQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.geodashboard.DashboardMetadataDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.geodashboard.DashboardMetadataDTO>)super.getResultSet();
}
}
