package com.runwaysdk.geodashboard;

@com.runwaysdk.business.ClassSignature(hash = -249005621)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to GeodashboardUser.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class GeodashboardUserQueryDTO extends com.runwaysdk.system.UsersQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = -249005621;

  protected GeodashboardUserQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.geodashboard.GeodashboardUserDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.geodashboard.GeodashboardUserDTO>)super.getResultSet();
}
}
