package com.runwaysdk.geodashboard;

@com.runwaysdk.business.ClassSignature(hash = -2100982855)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MappableClassGeoNode.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class MappableClassGeoNodeQueryDTO extends com.runwaysdk.business.RelationshipQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = -2100982855;

  protected MappableClassGeoNodeQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.geodashboard.MappableClassGeoNodeDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.geodashboard.MappableClassGeoNodeDTO>)super.getResultSet();
}
}
