package net.geoprism.graph;

@com.runwaysdk.business.ClassSignature(hash = 348008965)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AttributeBooleanTypeSnapshot.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class AttributeBooleanTypeSnapshotBase extends net.geoprism.graph.AttributeTypeSnapshot
{
  public final static String CLASS = "net.geoprism.graph.AttributeBooleanTypeSnapshot";
  @SuppressWarnings("unused")
  private static final long serialVersionUID = 348008965;
  
  public AttributeBooleanTypeSnapshotBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static AttributeBooleanTypeSnapshotQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    AttributeBooleanTypeSnapshotQuery query = new AttributeBooleanTypeSnapshotQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static AttributeBooleanTypeSnapshot get(String oid)
  {
    return (AttributeBooleanTypeSnapshot) com.runwaysdk.business.Business.get(oid);
  }
  
  public static AttributeBooleanTypeSnapshot getByKey(String key)
  {
    return (AttributeBooleanTypeSnapshot) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static AttributeBooleanTypeSnapshot lock(java.lang.String oid)
  {
    AttributeBooleanTypeSnapshot _instance = AttributeBooleanTypeSnapshot.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static AttributeBooleanTypeSnapshot unlock(java.lang.String oid)
  {
    AttributeBooleanTypeSnapshot _instance = AttributeBooleanTypeSnapshot.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
