package net.geoprism.graph;

@com.runwaysdk.business.ClassSignature(hash = -282598510)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ObjectTypeSnapshot.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class ObjectTypeSnapshotBase extends net.geoprism.graph.MetadataSnapshot
{
  public final static String CLASS = "net.geoprism.graph.ObjectTypeSnapshot";
  @SuppressWarnings("unused")
  private static final long serialVersionUID = -282598510;
  
  public ObjectTypeSnapshotBase()
  {
    super();
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static ObjectTypeSnapshotQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    ObjectTypeSnapshotQuery query = new ObjectTypeSnapshotQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static ObjectTypeSnapshot get(String oid)
  {
    return (ObjectTypeSnapshot) com.runwaysdk.business.Business.get(oid);
  }
  
  public static ObjectTypeSnapshot getByKey(String key)
  {
    return (ObjectTypeSnapshot) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static ObjectTypeSnapshot lock(java.lang.String oid)
  {
    ObjectTypeSnapshot _instance = ObjectTypeSnapshot.get(oid);
    _instance.lock();
    
    return _instance;
  }
  
  public static ObjectTypeSnapshot unlock(java.lang.String oid)
  {
    ObjectTypeSnapshot _instance = ObjectTypeSnapshot.get(oid);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
