package net.geoprism.registry.graph;

@com.runwaysdk.business.ClassSignature(hash = -2071555910)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AttributeDateValue.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class AttributeDateValueBase extends net.geoprism.registry.graph.AttributeBasicValue
{
  public final static String CLASS = "net.geoprism.registry.graph.AttributeDateValue";
  public final static java.lang.String VALUE = "value";
  @SuppressWarnings("unused")
  private static final long serialVersionUID = -2071555910;
  
  public AttributeDateValueBase()
  {
    super();
  }
  
  public java.util.Date getValue()
  {
    return (java.util.Date) this.getObjectValue(VALUE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDateTimeDAOIF getValueMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.graph.AttributeDateValue.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeDateTimeDAOIF)mdClassIF.definesAttribute(VALUE);
  }
  
  public void setValue(java.util.Date value)
  {
    this.setValue(VALUE, value);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static AttributeDateValue get(String oid)
  {
    return (AttributeDateValue) com.runwaysdk.business.graph.VertexObject.get(CLASS, oid);
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
