package net.geoprism.registry.graph;

@com.runwaysdk.business.ClassSignature(hash = -1607891883)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to AttributeBooleanValue.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class AttributeBooleanValueBase extends net.geoprism.registry.graph.AttributeBasicValue
{
  public final static String CLASS = "net.geoprism.registry.graph.AttributeBooleanValue";
  public final static java.lang.String VALUE = "value";
  @SuppressWarnings("unused")
  private static final long serialVersionUID = -1607891883;
  
  public AttributeBooleanValueBase()
  {
    super();
  }
  
  public Boolean getValue()
  {
    return (Boolean) this.getObjectValue(VALUE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeBooleanDAOIF getValueMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.graph.AttributeBooleanValue.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeBooleanDAOIF)mdClassIF.definesAttribute(VALUE);
  }
  
  public void setValue(Boolean value)
  {
    this.setValue(VALUE, value);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static AttributeBooleanValue get(String oid)
  {
    return (AttributeBooleanValue) com.runwaysdk.business.graph.VertexObject.get(CLASS, oid);
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
