/**
 * Copyright (c) 2023 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Geoprism(tm).
 *
 * Geoprism(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Geoprism(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Geoprism(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package net.geoprism.registry.graph;

@com.runwaysdk.business.ClassSignature(hash = -707731631)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ConceptSet.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class ConceptSetBase extends net.geoprism.registry.graph.SchemaElement
{
  public final static String CLASS = "net.geoprism.registry.graph.ConceptSet";
  public final static java.lang.String CODE = "code";
  public final static java.lang.String DESCRIPTION = "description";
  public final static java.lang.String DISPLAYLABEL = "displayLabel";
  public final static java.lang.String DISCRETETYPE = "discreteType";
  public final static java.lang.String ROOTTERM = "rootTerm";

  @SuppressWarnings("unused")
  private static final long serialVersionUID = -707731631;
  
  public ConceptSetBase()
  {
    super();
  }
  
  public String getCode()
  {
    return (String) this.getObjectValue(CODE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF getCodeMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.graph.ConceptSet.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeCharacterDAOIF)mdClassIF.definesAttribute(CODE);
  }
  
  public void setCode(String value)
  {
    this.setValue(CODE, value);
  }
  
  public com.runwaysdk.ComponentIF getDescription()
  {
    return (com.runwaysdk.ComponentIF) this.getObjectValue(DESCRIPTION);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getDescriptionMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.graph.ConceptSet.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeDAOIF)mdClassIF.definesAttribute(DESCRIPTION);
  }
  
  public void setDescription(com.runwaysdk.ComponentIF value)
  {
    this.setValue(DESCRIPTION, value);
  }
  
  public com.runwaysdk.ComponentIF getDisplayLabel()
  {
    return (com.runwaysdk.ComponentIF) this.getObjectValue(DISPLAYLABEL);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getDisplayLabelMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.graph.ConceptSet.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeDAOIF)mdClassIF.definesAttribute(DISPLAYLABEL);
  }
  
  public void setDisplayLabel(com.runwaysdk.ComponentIF value)
  {
    this.setValue(DISPLAYLABEL, value);
  }
  
  public String getDiscreteType()
  {
    return (String) this.getObjectValue(DISCRETETYPE);
  }

  public static com.runwaysdk.dataaccess.MdAttributeTextDAOIF getDiscreteTypeMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.graph.ConceptSet.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeTextDAOIF) mdClassIF.definesAttribute(DISCRETETYPE);
  }

  public void setDiscreteType(String value)
  {
    this.setValue(DISCRETETYPE, value);
  }
  
  public String getRootTerm()
  {
    return (String) this.getObjectValue(ROOTTERM);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeGraphReferenceDAOIF getRootTermMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(net.geoprism.registry.graph.ConceptSet.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeGraphReferenceDAOIF)mdClassIF.definesAttribute(ROOTTERM);
  }
  
  public void setRootTerm(net.geoprism.registry.graph.ConceptVertex value)
  {
    this.setValue(ROOTTERM, value);
  }
    

  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public com.runwaysdk.business.graph.EdgeObject addHasConceptChild(net.geoprism.registry.graph.ConceptClass conceptClass)
  {
    return super.addChild(conceptClass, "net.geoprism.registry.graph.HasConcept");
  }
  
  public void removeHasConceptChild(net.geoprism.registry.graph.ConceptClass conceptClass)
  {
    super.removeChild(conceptClass, "net.geoprism.registry.graph.HasConcept");
  }
  
  @SuppressWarnings("unchecked")
  public java.util.List<net.geoprism.registry.graph.ConceptClass> getHasConceptChildConceptClasss()
  {
    return super.getChildren("net.geoprism.registry.graph.HasConcept",net.geoprism.registry.graph.ConceptClass.class);
  }
  
  public com.runwaysdk.business.graph.EdgeObject addHasConceptEdgeChild(net.geoprism.registry.graph.ConceptEdgeType conceptEdgeType)
  {
    return super.addChild(conceptEdgeType, "net.geoprism.registry.graph.HasConceptEdge");
  }
  
  public void removeHasConceptEdgeChild(net.geoprism.registry.graph.ConceptEdgeType conceptEdgeType)
  {
    super.removeChild(conceptEdgeType, "net.geoprism.registry.graph.HasConceptEdge");
  }
  
  @SuppressWarnings("unchecked")
  public java.util.List<net.geoprism.registry.graph.ConceptEdgeType> getHasConceptEdgeChildConceptEdgeTypes()
  {
    return super.getChildren("net.geoprism.registry.graph.HasConceptEdge",net.geoprism.registry.graph.ConceptEdgeType.class);
  }
  
  public static ConceptSet get(String oid)
  {
    return (ConceptSet) com.runwaysdk.business.graph.VertexObject.get(CLASS, oid);
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
