package com.runwaysdk.geodashboard.ontology;

@com.runwaysdk.business.ClassSignature(hash = 381580621)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ClassifierHasSynonym.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ClassifierHasSynonymQueryDTO extends com.runwaysdk.business.RelationshipQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = 381580621;

  protected ClassifierHasSynonymQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends com.runwaysdk.geodashboard.ontology.ClassifierHasSynonymDTO> getResultSet()
{
  return (java.util.List<? extends com.runwaysdk.geodashboard.ontology.ClassifierHasSynonymDTO>)super.getResultSet();
}
}
