/**
 * Copyright (c) 2015 TerraFrame, Inc. All rights reserved.
 *
 * This file is part of Runway SDK(tm).
 *
 * Runway SDK(tm) is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * Runway SDK(tm) is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with Runway SDK(tm).  If not, see <http://www.gnu.org/licenses/>.
 */
package com.runwaysdk.geodashboard.gis.persist.condition;

@com.runwaysdk.business.ClassSignature(hash = 263555520)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DashboardAttributeCondition.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class DashboardAttributeConditionBase extends com.runwaysdk.geodashboard.gis.persist.condition.DashboardCondition implements com.runwaysdk.generation.loader.Reloadable
{
  public final static String CLASS = "com.runwaysdk.geodashboard.gis.persist.condition.DashboardAttributeCondition";
  public static java.lang.String DEFININGMDATTRIBUTE = "definingMdAttribute";
  private static final long serialVersionUID = 263555520;
  
  public DashboardAttributeConditionBase()
  {
    super();
  }
  
  public com.runwaysdk.system.metadata.MdAttribute getDefiningMdAttribute()
  {
    if (getValue(DEFININGMDATTRIBUTE).trim().equals(""))
    {
      return null;
    }
    else
    {
      return com.runwaysdk.system.metadata.MdAttribute.get(getValue(DEFININGMDATTRIBUTE));
    }
  }
  
  public String getDefiningMdAttributeId()
  {
    return getValue(DEFININGMDATTRIBUTE);
  }
  
  public void validateDefiningMdAttribute()
  {
    this.validateAttribute(DEFININGMDATTRIBUTE);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF getDefiningMdAttributeMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.geodashboard.gis.persist.condition.DashboardAttributeCondition.CLASS);
    return (com.runwaysdk.dataaccess.MdAttributeReferenceDAOIF)mdClassIF.definesAttribute(DEFININGMDATTRIBUTE);
  }
  
  public void setDefiningMdAttribute(com.runwaysdk.system.metadata.MdAttribute value)
  {
    if(value == null)
    {
      setValue(DEFININGMDATTRIBUTE, "");
    }
    else
    {
      setValue(DEFININGMDATTRIBUTE, value.getId());
    }
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public static DashboardAttributeConditionQuery getAllInstances(String sortAttribute, Boolean ascending, Integer pageSize, Integer pageNumber)
  {
    DashboardAttributeConditionQuery query = new DashboardAttributeConditionQuery(new com.runwaysdk.query.QueryFactory());
    com.runwaysdk.business.Entity.getAllInstances(query, sortAttribute, ascending, pageSize, pageNumber);
    return query;
  }
  
  public static DashboardAttributeCondition get(String id)
  {
    return (DashboardAttributeCondition) com.runwaysdk.business.Business.get(id);
  }
  
  public static DashboardAttributeCondition getByKey(String key)
  {
    return (DashboardAttributeCondition) com.runwaysdk.business.Business.get(CLASS, key);
  }
  
  public static DashboardAttributeCondition lock(java.lang.String id)
  {
    DashboardAttributeCondition _instance = DashboardAttributeCondition.get(id);
    _instance.lock();
    
    return _instance;
  }
  
  public static DashboardAttributeCondition unlock(java.lang.String id)
  {
    DashboardAttributeCondition _instance = DashboardAttributeCondition.get(id);
    _instance.unlock();
    
    return _instance;
  }
  
  public String toString()
  {
    if (this.isNew())
    {
      return "New: "+ this.getClassDisplayLabel();
    }
    else
    {
      return super.toString();
    }
  }
}
