package net.geoprism.data.etl;

@com.runwaysdk.business.ClassSignature(hash = -1799693249)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to UniversalAttributeBinding.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class UniversalAttributeBindingQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = -1799693249;

  protected UniversalAttributeBindingQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.data.etl.UniversalAttributeBindingDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.data.etl.UniversalAttributeBindingDTO>)super.getResultSet();
}
}
