package net.geoprism;

@com.runwaysdk.business.ClassSignature(hash = -535135970)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to ForgotPasswordRequest.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class ForgotPasswordRequestQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = -535135970;

  protected ForgotPasswordRequestQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.ForgotPasswordRequestDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.ForgotPasswordRequestDTO>)super.getResultSet();
}
}
