package com.runwaysdk.geodashboard.report;

@com.runwaysdk.business.ClassSignature(hash = 2083230688)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to MissingReportDesignException.java
 *
 * @author Autogenerated by RunwaySDK
 */
public abstract class MissingReportDesignExceptionBase extends com.runwaysdk.business.SmartException implements com.runwaysdk.generation.loader.Reloadable
{
  public final static String CLASS = "com.runwaysdk.geodashboard.report.MissingReportDesignException";
  public static java.lang.String ID = "id";
  private static final long serialVersionUID = 2083230688;
  
  public MissingReportDesignExceptionBase()
  {
    super();
  }
  
  public MissingReportDesignExceptionBase(java.lang.String developerMessage)
  {
    super(developerMessage);
  }
  
  public MissingReportDesignExceptionBase(java.lang.String developerMessage, java.lang.Throwable cause)
  {
    super(developerMessage, cause);
  }
  
  public MissingReportDesignExceptionBase(java.lang.Throwable cause)
  {
    super(cause);
  }
  
  public String getId()
  {
    return getValue(ID);
  }
  
  public void validateId()
  {
    this.validateAttribute(ID);
  }
  
  public static com.runwaysdk.dataaccess.MdAttributeDAOIF getIdMd()
  {
    com.runwaysdk.dataaccess.MdClassDAOIF mdClassIF = com.runwaysdk.dataaccess.metadata.MdClassDAO.getMdClassDAO(com.runwaysdk.geodashboard.report.MissingReportDesignException.CLASS);
    return mdClassIF.definesAttribute(ID);
  }
  
  protected String getDeclaredType()
  {
    return CLASS;
  }
  
  public java.lang.String localize(java.util.Locale locale)
  {
    java.lang.String message = super.localize(locale);
    message = replace(message, "{id}", this.getId());
    return message;
  }
  
}
