package net.geoprism.dashboard;

@com.runwaysdk.business.ClassSignature(hash = 145310597)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to DashboardMetadata.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class DashboardMetadataQueryDTO extends com.runwaysdk.business.RelationshipQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = 145310597;

  protected DashboardMetadataQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.dashboard.DashboardMetadataDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.dashboard.DashboardMetadataDTO>)super.getResultSet();
}
}
