package net.geoprism.dhis2;

@com.runwaysdk.business.ClassSignature(hash = 1162410791)
/**
 * This class is generated automatically.
 * DO NOT MAKE CHANGES TO IT - THEY WILL BE OVERWRITTEN
 * Custom business logic should be added to OptionCodeMapping.java
 *
 * @author Autogenerated by RunwaySDK
 */
public class OptionCodeMappingQueryDTO extends com.runwaysdk.business.BusinessQueryDTO
 implements com.runwaysdk.generation.loader.Reloadable
{
private static final long serialVersionUID = 1162410791;

  protected OptionCodeMappingQueryDTO(String type)
  {
    super(type);
  }

@SuppressWarnings("unchecked")
public java.util.List<? extends net.geoprism.dhis2.OptionCodeMappingDTO> getResultSet()
{
  return (java.util.List<? extends net.geoprism.dhis2.OptionCodeMappingDTO>)super.getResultSet();
}
}
